name: Export iOS IPA

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Resolve Swift packages
        run: |
          xcodebuild \
            -project maciOS.xcodeproj \
            -scheme maciOS \
            -resolvePackageDependencies

      - name: Build AppKit-iOS
        run: |
          xcodebuild \
            -project AppKit/AppKit-iOS.xcodeproj \
            -scheme AppKit-iOS \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" DEVELOPMENT_TEAM=""
            clean build

      - name: Archive app
        run: |
          xcodebuild \
            -project maciOS.xcodeproj \
            -scheme maciOS \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/maciOS.xcarchive \
            clean archive

      - name: Export IPA (unsigned)
        run: |
          xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/maciOS.xcarchive \
            -exportPath $PWD/build/ipa \
            -exportOptionsPlist exportOptions.plist
          
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: maciOS-ipa
          path: build/ipa
